-- MySQL Script generated by MySQL Workbench
-- Thu Mar 26 07:15:01 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `dt_cadastro` DATE NOT NULL,
  `rua` VARCHAR(100) NOT NULL,
  `endereco` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`telefones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`telefones` (
  `id_telefone` INT NOT NULL AUTO_INCREMENT,
  `ddd` CHAR(2) NOT NULL,
  `telefone` VARCHAR(9) NOT NULL,
  `id_cliente` INT NOT NULL,
  `clientes_id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_telefone`),
  INDEX `fk_telefones_clientes_idx` (`clientes_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_telefones_clientes`
    FOREIGN KEY (`clientes_id_cliente`)
    REFERENCES `mydb`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fabricantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fabricantes` (
  `id_fabricante` INT NOT NULL AUTO_INCREMENT,
  `nome_fabricante` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id_fabricante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produtos` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `nome_produto` VARCHAR(100) NOT NULL,
  `fabricantes_id_fabricante` INT NOT NULL,
  PRIMARY KEY (`id_produto`),
  INDEX `fk_produtos_fabricantes2_idx` (`fabricantes_id_fabricante` ASC) VISIBLE,
  CONSTRAINT `fk_produtos_fabricantes2`
    FOREIGN KEY (`fabricantes_id_fabricante`)
    REFERENCES `mydb`.`fabricantes` (`id_fabricante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vendas` (
  `id_venda` INT NOT NULL AUTO_INCREMENT,
  `dt_venda` DATE NOT NULL,
  `venda_total` DECIMAL(10,2) NOT NULL,
  `clientes_id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_venda`),
  INDEX `fk_vendas_clientes1_idx` (`clientes_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_vendas_clientes1`
    FOREIGN KEY (`clientes_id_cliente`)
    REFERENCES `mydb`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produtos` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `nome_produto` VARCHAR(100) NOT NULL,
  `fabricantes_id_fabricante` INT NOT NULL,
  PRIMARY KEY (`id_produto`),
  INDEX `fk_produtos_fabricantes2_idx` (`fabricantes_id_fabricante` ASC) VISIBLE,
  CONSTRAINT `fk_produtos_fabricantes2`
    FOREIGN KEY (`fabricantes_id_fabricante`)
    REFERENCES `mydb`.`fabricantes` (`id_fabricante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`itens_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`itens_venda` (
  `id_item` INT NOT NULL AUTO_INCREMENT,
  `quantidade` INT NOT NULL,
  `vendas_id_venda` INT NOT NULL,
  `produtos_id_produto` INT NOT NULL,
  `produtos_id_produto1` INT NOT NULL,
  PRIMARY KEY (`id_item`),
  INDEX `fk_itens_venda_vendas1_idx` (`vendas_id_venda` ASC) VISIBLE,
  INDEX `fk_itens_venda_produtos1_idx` (`produtos_id_produto` ASC) VISIBLE,
  INDEX `fk_itens_venda_produtos2_idx` (`produtos_id_produto1` ASC) VISIBLE,
  CONSTRAINT `fk_itens_venda_vendas1`
    FOREIGN KEY (`vendas_id_venda`)
    REFERENCES `mydb`.`vendas` (`id_venda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itens_venda_produtos1`
    FOREIGN KEY (`produtos_id_produto`)
    REFERENCES `mydb`.`produtos` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itens_venda_produtos2`
    FOREIGN KEY (`produtos_id_produto1`)
    REFERENCES `mydb`.`produtos` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
