-- MySQL Script generated by MySQL Workbench
-- Wed Apr  8 08:27:52 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `dt_cadastro` DATETIME NOT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`endereco` (
  `id-endereco` INT NOT NULL AUTO_INCREMENT,
  `longradouro` VARCHAR(100) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `cidade` VARCHAR(50) NOT NULL,
  `estado` CHAR(2) NOT NULL,
  `cep` CHAR(11) NOT NULL,
  `tipo_endereco` ENUM('Residencial', 'Comercial') NULL,
  `clientes_id_cliente` INT NOT NULL,
  PRIMARY KEY (`id-endereco`, `clientes_id_cliente`),
  INDEX `fk_endereco_clientes1_idx` (`clientes_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_endereco_clientes1`
    FOREIGN KEY (`clientes_id_cliente`)
    REFERENCES `mydb`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`conta` (
  `id_conta` INT NOT NULL AUTO_INCREMENT,
  `numero_conta` CHAR(10) NOT NULL,
  `agencia` CHAR(4) NOT NULL,
  `saldo` DECIMAL(10,2) NOT NULL,
  `tipo_conta` ENUM('Conta Corrente', 'Conta Poupança', 'Conta Pessoa Juridica') NOT NULL,
  `clientes_id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_conta`, `clientes_id_cliente`),
  INDEX `fk_conta_clientes1_idx` (`clientes_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_conta_clientes1`
    FOREIGN KEY (`clientes_id_cliente`)
    REFERENCES `mydb`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`telefones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`telefones` (
  `id_telefone` INT NOT NULL AUTO_INCREMENT,
  `ddd` CHAR(2) NOT NULL,
  `numero` CHAR(2) NOT NULL,
  `tipo_telefone` ENUM('Particular', 'Residencial', 'Comercial') NOT NULL,
  `clientes_id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_telefone`, `clientes_id_cliente`),
  INDEX `fk_telefones_clientes_idx` (`clientes_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_telefones_clientes`
    FOREIGN KEY (`clientes_id_cliente`)
    REFERENCES `mydb`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`emails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`emails` (
  `id_email` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(64) NOT NULL,
  `clientes_id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_email`, `clientes_id_cliente`),
  INDEX `fk_emails_clientes1_idx` (`clientes_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_emails_clientes1`
    FOREIGN KEY (`clientes_id_cliente`)
    REFERENCES `mydb`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`transacao` (
  `id_transacao` INT NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL(10,2) NOT NULL,
  `conta_id_conta` INT NOT NULL,
  `conta_clientes_id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_transacao`, `conta_id_conta`, `conta_clientes_id_cliente`),
  INDEX `fk_transacao_conta1_idx` (`conta_id_conta` ASC, `conta_clientes_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_transacao_conta1`
    FOREIGN KEY (`conta_id_conta` , `conta_clientes_id_cliente`)
    REFERENCES `mydb`.`conta` (`id_conta` , `clientes_id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
